[build]
  command = "npm run build"
  publish = "public"

[context.production.environment]
  REACT_APP_CONTENTFUL_ACCESS_TOKEN = process.env.REACT_APP_CONTENTFUL_ACCESS_TOKEN
  REACT_APP_CONTENTFUL_SPACE_ID = process.env.REACT_APP_CONTENTFUL_SPACE_ID
